language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
node_js:
  - '14'
  - '12'
  - '10'
before_script:
  - greenkeeper-lockfile-update
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
